name: Issue details
on:
    issues:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Print github context
              run: echo "${{ toJSON(github) }}"

            - name: Print issue details
              run: echo "Issue ${{ issue.id }} ${{ action }} with title ${{ issue.title }}"

            