name: Issue details
on: issues

jobs:
    show:
        runs-on: ubuntu-latest
        steps:
            - name: Print github context
              run: echo "${{ toJSON(github) }}"

            - name: Print issue details
              run: echo "Issue \#${{  github.event.issue.id }} ${{ github.event.action }} with title ${{ github.event.issue.title }}"

            